#ifndef _CHOOCHOO_H_
#define _CHOOCHOO_H_


#define      VAGN_E "                              "

#define LAST_VAGN0  "        @@@@@    @@@@@        "
#define LAST_VAGN1  "  @@   @     @  @     @   @@  "
#define LAST_VAGN2  "  @ @@@@@@@@@@@@@@@@@@@@@@ @  "
#define LAST_VAGN3  "  @@@ @                @ @@@  "
#define LAST_VAGN4  "    @ @ @@ @ @   @ @ @ @ @    "
#define LAST_VAGN5  "    @ @                @ @    "
#define LAST_VAGN6  "    @ @   @    @@ @ @@ @ @    "
#define LAST_VAGN7  "   @@ @                @ @@   "
#define LAST_VAGN8  "  @ @ @                @ @ @  "
#define LAST_VAGN9  "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
#define LAST_VAGN10 "@ @                        @ @"
#define LAST_VAGN11 "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ "
#define LAST_VAGN12 "@@ @   @ @   @  @   @ @   @ @@"
#define LAST_VAGN13 "   @   @@@   @  @   @@@   @   "
#define LAST_VAGN14 "    @@@   @@@    @@@   @@@    "

#define MIDDLE_VAGN_E "                                "
#define MIDDLE_VAGN0  "        @@@@@    @@@@@          "
#define MIDDLE_VAGN1  "  @@   @     @  @     @   @@    "
#define MIDDLE_VAGN2  "  @ @@@@@@@@@@@@@@@@@@@@@@ @    "
#define MIDDLE_VAGN3  "  @@@ @                @ @@@    "
#define MIDDLE_VAGN4  "    @ @ @@ @ @   @ @ @ @ @      "
#define MIDDLE_VAGN5  "    @ @                @ @      "
#define MIDDLE_VAGN6  "    @ @   @    @@ @ @@ @ @      "
#define MIDDLE_VAGN7  "   @@ @                @ @@     "
#define MIDDLE_VAGN8  "  @ @ @                @ @ @    "
#define MIDDLE_VAGN9  "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  "
#define MIDDLE_VAGN10 "@ @                        @ @@@"
#define MIDDLE_VAGN11 "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
#define MIDDLE_VAGN12 "@@ @   @ @   @  @   @ @   @ @@  "
#define MIDDLE_VAGN13 "   @   @@@   @  @   @@@   @     "
#define MIDDLE_VAGN14 "    @@@   @@@    @@@   @@@      "


#define SMOKE0_0 "                   @@@@   @@@     @@      @     @       @        @"
#define SMOKE1_0 "                                                                  "
#define SMOKE2_0 "             @@@@                                                 "
#define SMOKE3_0 "                                                                  "
#define SMOKE4_0 "          @@                                                      "
#define SMOKE0_1 "                      @@@@    @@@     @      @       @      @     "
#define SMOKE1_1 "                 @@@@                                             "
#define SMOKE2_1 "                                                                  "
#define SMOKE3_1 "            @@@                                                   "
#define SMOKE4_1 "                                                                  "

#define LOK_EMPTY "                                               "

#define LOK0     "         @@@@                                  " 
#define LOK1     "        @    @          @@@@@@     @@@@@@@@@@@@" 
#define LOK2     "         @  @           @    @    @           @" 
#define LOK3     "         @  @           @    @  @ @@@@@@@@@@@@ " 
#define LOK4     "     @@@ @  @ @@@@      @    @ @ @ @   @  @    " 
#define LOK5     "     @ @ @  @ @  @  @   @    @ @ @ @   @  @    " 
#define LOK6     "     @ @ @  @ @  @ @ @ @@    @@@@@@@   @  @    " 
#define LOK7     "     @@@@@  @@@  @@@@@@@ @@@@ @    @   @  @    " 
#define LOK8     "    @     @@ @ @@      @      @    @@@@@@@@    " 
#define LOK9     "   @         @         @      @    @      @    " 
#define LOK10    "   @         @         @      @    @      @    " 
#define LOK11    "   @         @                     @      @    " 
#define LOK12    "    @        @     @@@     @@@     @@@    @    " 

#define LOK13_0  "     @@@@@@@@@    @   @   @   @   @   @@@@@@@  " 
#define LOK14_0  "  @@@    @   @@@@@     @ @     @ @     @  @ @@@" 
#define LOK15_0  " @   @@@@@@@@@@  @@@@@@@@@@@@@@@@@@    @  @@@@@" 
#define LOK16_0  "@    @ @  @ @  @ @     @ @     @ @     @@@ @@  " 
#define LOK17_0  "@@@@@@ @  @@@  @  @   @   @   @   @   @        " 

#define LOK13_1  "     @@@@@@@@@    @   @   @   @   @   @@@@@@@  " 
#define LOK14_1  "  @@@    @   @@@@@     @ @     @ @     @  @ @@@" 
#define LOK15_1  " @   @@@@@@@@@@  @     @ @     @ @     @  @@@@@" 
#define LOK16_1  "@    @ @  @ @  @ @     @ @     @ @     @@@ @@  " 
#define LOK17_1  "@@@@@@ @  @@@  @  @ @@@@@@@@@@@@@@@@@ @        " 

#define LOK13_2  "     @@@@@@@@@    @   @   @   @   @   @@@@@@@  " 
#define LOK14_2  "  @@@    @   @@@@@     @ @     @ @     @  @ @@@" 
#define LOK15_2  " @   @@@@@@@@@@  @    @@@@@@@@@@@@@@@@@@  @@@@@" 
#define LOK16_2  "@    @ @  @ @  @ @     @ @     @ @     @@@ @@  " 
#define LOK17_2  "@@@@@@ @  @@@  @  @   @   @   @   @   @        " 

#define LOK13_3  "     @@@@@@@@@    @ @@@@@@@@@@@@@@@@@ @@@@@@@  " 
#define LOK14_3  "  @@@    @   @@@@@     @ @     @ @     @  @ @@@" 
#define LOK15_3  " @   @@@@@@@@@@  @     @ @     @ @     @  @@@@@" 
#define LOK16_3  "@    @ @  @ @  @ @     @ @     @ @     @@@ @@  " 
#define LOK17_3  "@@@@@@ @  @@@  @  @   @   @   @   @   @        " 

#define LOK18    "        @@   @@    @@@     @@@     @@@         " 


#endif